# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7d3086ad09130fff794858d9f8e3b6579fb665f498ec8b404b34a963f454b5725ee069844221211f95c404c69e71d3700902675801cc51554f7dcd2046596fa7

test:
  secret_key_base: c7139389332104da2187949806d89f5f40578343172b6ec673dd22773754abfc8e1473809ff551c718f1fa314a07bcd9c6af7c2db610f844d57893077cc4de0e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
